export const CLEAR_VENUES = 'CLEAR_VENUES';
export const REQUEST_VENUES = 'REQUEST_VENUES';
export const RECEIVE_VENUES = 'RECEIVE_VENUES';
export const GEOLOCATION_FAILED = 'GEOLOCATION_FAILED';


export const RECEIVE_LOCATION = 'RECEIVE_LOCATION';
